[libdefaults]
 default_realm = ZAP.TEST
 dns_lookup_realm = false
 dns_lookup_kdc = false
 rdns = false
 forwardable = true

[realms]
 ZAP.TEST = {
  kdc = kerberos-kdc.zap.test
  admin_server = kerberos-kdc.zap.test
 }

[domain_realm]
 .zap.test = ZAP.TEST
 zap.test = ZAP.TEST
