using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
var builder=WebApplication.CreateBuilder(args); builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(o=>o.LoginPath="/login"); builder.Services.AddAuthorization(); builder.Services.AddAntiforgery(); var app=builder.Build(); app.UseAuthentication(); app.UseAuthorization();
app.MapGet("/login",(HttpContext c, Microsoft.AspNetCore.Antiforgery.IAntiforgery af)=>{var t=af.GetAndStoreTokens(c);return Results.Content($"""<!doctype html><html><body><h1>ASP.NET Form Login</h1><form method='post' action='/login'><input type='hidden' name='{t.FormFieldName}' value='{t.RequestToken}'><label>Username <input name='username' autocomplete='username'></label><br><label>Password <input type='password' name='password' autocomplete='current-password'></label><br><button>Sign in</button></form></body></html>""","text/html");});
app.MapPost("/login",async (HttpContext c, Microsoft.AspNetCore.Antiforgery.IAntiforgery af)=>{await af.ValidateRequestAsync(c);var f=await c.Request.ReadFormAsync();if(f["username"]=="zapuser"&&f["password"]=="ZapTest123!"){var id=new ClaimsIdentity(new[]{new Claim(ClaimTypes.Name,"zapuser")},CookieAuthenticationDefaults.AuthenticationScheme);await c.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,new ClaimsPrincipal(id));return Results.Redirect("/private");}return Results.Unauthorized();});
app.MapGet("/private",(HttpContext c)=>c.User.Identity?.IsAuthenticated==true?Results.Content("<h1>AUTHENTICATED</h1><p>user=zapuser</p><p>technology=ASPNET_CORE</p><a href='/api/whoami'>whoami</a>","text/html"):Results.Redirect("/login"));
app.MapGet("/api/whoami",(HttpContext c)=>Results.Json(c.User.Identity?.IsAuthenticated==true?new {authenticated=true,username=c.User.Identity.Name,technology="ASPNET_CORE"}:new {authenticated=false,technology="ASPNET_CORE"}));
app.MapGet("/logout",async (HttpContext c)=>{await c.SignOutAsync();return Results.Redirect("/login");}); app.Run();
