const http=require('http');const crypto=require('crypto');const {URL}=require('url');
const PORT=Number(process.env.PORT||3000),SCENARIO=process.env.SCENARIO||'jwt-exp',USERNAME='zapuser',PASSWORD='ZapTest123!',CONTROL_TOKEN=process.env.TESTBED_CONTROL_TOKEN||'zap-testbed-reset-v1';
const tokens=new Map();const EXPECTED=['/private','/api/profile','/api/orders','/api/documents'];const hits=new Map();
const auth={loginAttempts:0,successfulLogins:0,failedLogins:0,tokenChecks:0,authenticatedRequests:0,unauthorizedRequests:0,expiredTokenRequests:0,tokensIssued:0};
const scenarioConfig={'jwt-exp':{ttlSeconds:12,format:'jwt'},'timeout':{ttlSeconds:120,format:'opaque'},'check':{ttlSeconds:8,format:'opaque'}};const cfg=scenarioConfig[SCENARIO];if(!cfg)throw new Error(`Unknown SCENARIO=${SCENARIO}`);
function json(res,s,b,h={}){res.writeHead(s,{'Content-Type':'application/json; charset=utf-8',...h});res.end(JSON.stringify(b))}function html(res,s,b){res.writeHead(s,{'Content-Type':'text/html; charset=utf-8'});res.end(`<!doctype html><html><body style="font-family:sans-serif;max-width:760px;margin:48px auto">${b}</body></html>`)}
function readJson(req){return new Promise((ok,fail)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch{ok({})}});req.on('error',fail)})}function b64url(v){return Buffer.from(v).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function issueToken(){const now=Math.floor(Date.now()/1000),exp=now+cfg.ttlSeconds,id=crypto.randomUUID();let token=cfg.format==='jwt'?`${b64url(JSON.stringify({alg:'none',typ:'JWT'}))}.${b64url(JSON.stringify({sub:USERNAME,iat:now,exp,jti:id}))}.`:`zap-${SCENARIO}-${id}`;tokens.set(token,{username:USERNAME,expiresAt:exp*1000});auth.tokensIssued++;return{token,exp}}
function bearer(req){const a=req.headers.authorization||'';return a.startsWith('Bearer ')?a.slice(7):null}
function validateToken(token){const e=token&&tokens.get(token);if(!e)return {entry:null,expired:false};if(Date.now()>=e.expiresAt){tokens.delete(token);return{entry:null,expired:true}}return{entry:e,expired:false}}
function requireAuth(req,res,kind){const v=validateToken(bearer(req));if(!v.entry){auth.unauthorizedRequests++;if(v.expired)auth.expiredTokenRequests++;json(res,401,{authenticated:false,scenario:SCENARIO,kind},{'WWW-Authenticate':'Bearer realm="ZAP-SCRIPT-LAB"'});return null}auth.authenticatedRequests++;return v.entry}
function track(p){if(EXPECTED.includes(p))hits.set(p,(hits.get(p)||0)+1)}function coverage(){const v=EXPECTED.filter(p=>hits.has(p));let valid=0;for(const[t]of tokens)if(validateToken(t).entry)valid++;return{application:`script-${SCENARIO}`,scenario:SCENARIO,discovery:{expected:EXPECTED.length,visited:v.length,coveragePercent:Number((v.length*100/EXPECTED.length).toFixed(2)),visitedEndpoints:v,missingEndpoints:EXPECTED.filter(p=>!hits.has(p))},authentication:{...auth,validTokens:valid,ttlSeconds:cfg.ttlSeconds}}}
function reset(){hits.clear();tokens.clear();Object.keys(auth).forEach(k=>auth[k]=0)}
async function handle(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;
 if(p==='/health')return json(res,200,{ok:true,scenario:SCENARIO,ttlSeconds:cfg.ttlSeconds,format:cfg.format});if(p==='/__testbed/expected'&&req.method==='GET')return json(res,200,{application:`script-${SCENARIO}`,expectedEndpoints:EXPECTED});if(p==='/__testbed/coverage'&&req.method==='GET')return json(res,200,coverage());if(p==='/__testbed/control/reset'&&req.method==='POST'){if(req.headers['x-testbed-control']!==CONTROL_TOKEN)return json(res,404,{error:'not found'});reset();return json(res,200,{reset:true,application:`script-${SCENARIO}`})}
 if(req.method==='POST'&&p==='/api/login'){auth.loginAttempts++;const b=await readJson(req);if(b.username!==USERNAME||b.password!==PASSWORD){auth.failedLogins++;return json(res,401,{status:'fail',message:'bad credentials'})}auth.successfulLogins++;const x=issueToken();return json(res,200,{status:'success',auth_token:x.token,token_type:'Bearer',expires_in:cfg.ttlSeconds,expires_at:x.exp,scenario:SCENARIO})}
 if(req.method==='GET'&&p==='/me'){auth.tokenChecks++;const e=requireAuth(req,res,'token-check');if(!e)return;return json(res,200,{authenticated:true,username:e.username,scenario:SCENARIO})}
 if(req.method==='GET'&&p==='/api/whoami'){const e=requireAuth(req,res,'whoami');if(!e)return;return json(res,200,{authenticated:true,username:e.username,scenario:SCENARIO})}
 if(req.method==='GET'&&p==='/private'){track(p);const e=requireAuth(req,res,'private');if(!e)return;return html(res,200,`<h1>AUTHENTICATED</h1><p>${SCENARIO}</p><ul><li><a href="/api/profile">profile</a></li><li><a href="/api/orders">orders</a></li><li><a href="/api/documents">documents</a></li></ul>`)}
 if(req.method==='GET'&&['/api/profile','/api/orders','/api/documents'].includes(p)){track(p);const e=requireAuth(req,res,p.slice(1));if(!e)return;return json(res,200,{authenticated:true,username:e.username,endpoint:p,scenario:SCENARIO})}
 if(req.method==='GET'&&p==='/api/stats')return json(res,200,coverage().authentication);if(req.method==='POST'&&p==='/logout'){const t=bearer(req);if(t)tokens.delete(t);return json(res,200,{ok:true})}
 if(p==='/'||p==='/login')return html(res,200,`<h1>ZAP HttpSender token lab</h1><p>scenario=${SCENARIO}</p><a href="/private">protected entry</a>`);return json(res,404,{error:'not found',scenario:SCENARIO})}
http.createServer((q,s)=>handle(q,s).catch(e=>{console.error(e);json(s,500,{error:String(e),scenario:SCENARIO})})).listen(PORT,'0.0.0.0',()=>console.log(`script-auth-token-lab scenario=${SCENARIO} port=${PORT}`));
